### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by cKlee** [melgi/cturtle#10]
Installing with makes exits with error:

with the current master branch

    g++ -c  -O2 -Wall -march=native -std=c++11 -o obj/Utf8.o src/Utf8.cc
    src/Utf8.cc:26:10: error: expected constructor, destructor, or type conversion before ‘(’ token
    src/Utf8.cc:39:10: error: expected constructor, destructor, or type conversion before ‘(’ token
    make: *** [obj/Utf8.o] Errors 1

and with the 1.0.5 release:

    g++ -c  -O2 -Wall -march=native -std=c++11 -o obj/Main.o src/Main.cc
    In file included from src/Parser.hh:27:0,
                      from src/Main.cc:25:
    src/Model.hh:189:3: error: looser throw specifier for ‘virtual turtle::RDFList::~RDFList()’
    src/Model.hh:75:9: error:   overriding ‘virtual turtle::Resource::~Resource() noexcept (true)’
    make: *** [obj/Main.o] Errors 1

I want to install cturtle for usage wit EYE on debian. Thanks!

**Comment by melgi** [comment]
Hi,

What version of g++ are you using? It does not seem to support [alignas](http://en.cppreference.com/w/cpp/language/alignas).  I removed them in the master branch, but I am afraid that if your compiler is too old, you will run into other issues. (It requires g++ 4.8)

Thanks.

**Comment by cKlee** [comment]
It's working with g++ version 4.9. Thanks!
